### PR TITLE
Add tray options

### PR DESCRIPTION
**Pull request by oleitao**
Hi, 

This is my first contribution to this project. if you allow, I would like to contribute with new improvements and features to this application.

I have added an option to keep the app running as a tray icon, so if the user wants to re-open the application to add new taskbar icons, it can be done more easily.

Let me know if you have any suggestions, you would like me to help with.

Happy new year ;-)!

### CODE REVIEW

**Comment by PikeNote** [comment]
I had taken a look at it and I am curious, for frmClient.resx, is there any way to use the resource files already in the project instead of using the base64 encoded version? I thought it most likely would make it a bit cleaner.

**Comment by tjackenpacken** [comment]
Hi! 

I'm glad you want to help with the project. The general idea seems great, but that .resx file is really an eyesore. So I'll second Pike's question above!

Happy new year!

**Comment by oleitao** [comment]
Hi!

You are right, I have update my branch, by removing all those changes to the .resx file and maintaining the tray icon.

Glad to contribute :-D!

**Comment by PikeNote** [comment]
Hello! I had recently built and tested it. I think it would be good to not add any more buttons/controls but rather use the native close function and cancel the input from that to close the window. It avoids hacky create parameter solutions to remove the existing exit buttons and simplifies the process.

```
private void frmClient_FormClosing(object sender, FormClosingEventArgs e) {
      Hide();
      trayIcon.Visible = true;
}
```

On top of that I think you should add a event to the tray icon so when its clicked, it can bring up the window automatically.

That is about it and this is a great idea! In the future I may look to support settings for the entire client to say turn off this feature but I am not sure currently how to handle such thing yet. Want to get a proper format going before adding any settings.

**Comment by oleitao** [comment]
Hi, 

I have made a new approach of the "close to tray" feature.

**Comment by PikeNote** [comment]
Looks good but I have a few concerns/suggestions currently that I can think of.

First the tray options seem to appear at the top left of my screen for some reason instead of above the application as the expected behavior is.

Second, I think the application should be launched when first ran instead of only opening in the tray. It takes more steps to open it which may hinder user experience.

Third, I think you should just be able to (if possible) a normal click would just bring up the application automatically without having to click another button and right click be assigned to opening the context menu with the exit. I believe it would make the use a bit more streamlined.

Great work thusfar!

**Comment by oleitao** [comment]
Hi @PikeNote, thanks you,

Well pointed 👍. Fixed the top left screen tray menu. 
For some reason in my machine was working fine, but when tested on a clean machine (without any previous installation), the issue was there.

Implemented the launch order you suggested, opening the app on first initialization and then on close put it in tray.

Next commit, I will implement the option to display/expand the window, when tray icon is double clicked.

**Comment by oleitao** [comment]
Hi @PikeNote and @tjackenpacken.

Added some new commits, fixing some previous tray issues and adding the launch on tray click.

**Comment by tjackenpacken** [comment]
> 
> 
> Hi @PikeNote and @tjackenpacken.
> 
> Added some new commits, fixing some previous tray issues and adding the launch on tray click.

Hi!

I have been busy with some school assignments the past couple of weeks, but will have some more time now. Will try to look into your pull later today. Is your forked repository the latest release + your pull?

**Comment by oleitao** [comment]
Hi @tjackenpacken, no worries.  

Yes the fork repo is update with you `master` branch and synced with my branch `add-tray-options`

**Pull request closed without merging**
