### PR TITLE
Folder Shortcut Support

### PR DESCRIPTION
**Pull request by pikent**
- Fully support folder shortcuts (only drag drop currently) ( #29 )
- Cleaned up some pieces of code and removed unnecessary dependencies

### CODE REVIEW

**Comment by xXNicksonXx** [comment]
I builded the current state of the code by myself and found a bug, i have a group of 13 shortcuts, but when I edit the group only 8 of them get initially loaded. If I delete 1, then all of them get loaded.
image

**Comment by pikent** [comment]
I will look into trying to reproduce it. I will update you on any progress on the matter and I will seek to fix it within this pull. 

To clarify, the steps are
1) Load 13 shortcuts
2) Edit group (Only 8 get loaded)
3) Delete 1 (All of them get loaded back)

I will get back to you asap.

**Comment by xXNicksonXx** [comment]
I did some more testing. I was wrong, it has nothing to do with the changes from your last pullrequest, the bug is also in the latest release.

I fixed the issue like that in the frmGroup.cs file:
Before
before
After
after

**Comment by pikent** [comment]
Thanks for the fix! I had been quite stumped at it for quite some time as I was unsure why it was doing that. The y position didn't cross my mind even though at one point I was looking at it in debug. I am still confused to as why if that is the case that any updates like moving index would fix it. The same process is done after all the controls are cleared and yet the second time around everything generates in fine. I have applied the fix as described above and gave credit in the description.

**Comment by tjackenpacken** [comment]
> 
> 
> I did some more testing. I was wrong, it has nothing to do with the changes from your last pullrequest, the bug is also in the latest release.
> 
> The problem is, that the y position for the next shortcut only increases if there is enough space.
> I fixed the issue like that in the frmGroup.cs file:


I was baffled as to why i had written it like that, until now that i tried it out and remember the error i was trying to avoid: 
bild


For some reason, after the 8th shortcut it's starting to create additional space between each shortcuts. For each additional shortcut the extra space grows by 1 y.

**Comment by tjackenpacken** [comment]
> For some reason, after the 8th shortcut it's starting to create additional space between each shortcuts. For each additional shortcut the extra space grows by 1 y.

Ok this seem to be because of the ScrollControlIntoView... I am reworking these methods completely instead.

**Pull request merged**
